#!/usr/bin/env sh
location="$1"; [ -z "$location" ] || { location="$location+" && rm -f "$HOME/.local/share/weatherreport" ;}

getforecast() { curl -s "wttr.in/$location" > "$HOME/.local/share/weatherreport" || exit 1 ;}

showweather() { 
  rain=$(sed '16q;d' "$HOME/.local/share/weatherreport" | grep -wo "[0-9]*%" )

  TIME=$(date "+%H")
  if [ $TIME -lt 6 ]; then
    y=$(echo $rain | awk '{print $1}' | sed -e "s/^/ /g" | tr -d '\n')
  elif [ $TIME -lt 12 ]]; then
    y=$(echo $rain | awk '{print $2}' | sed -e "s/^/ /g" | tr -d '\n')
  elif [ $TIME -lt 18 ]]; then
    y=$(echo $rain | awk '{print $3}' | sed -e "s/^/ /g" | tr -d '\n')
  else
    y=$(echo $rain | awk '{print $4}' | sed -e "s/^/ /g" | tr -d '\n')
  fi

  printf "<span color='#97bbf7'>%s" "$y"

  currentTemp=$(sed '4q;d' "$HOME/.local/share/weatherreport" | grep -o "m\\(-\\)*[0-9]")
  #echo $currentTemp
  #echo $var

  sed '13q;d' "$HOME/.local/share/weatherreport" | grep -o "m\\(-\\)*[0-9]\\+" | sort -n -t 'm' -k 2n | sed -e 1b -e '$!d' | tr '\n|m' ' ' | awk '{print " ",$1 "°","",$2 "°</span>"}' ;}

case $BLOCK_BUTTON in
    1) $TERMINAL -x 'zsh -c "less -rS $HOME/.local/share/weatherreport"' ;;
    2) getforecast && showweather ;;
    3) pgrep -x dunst >/dev/null && notify-send "Weather module" \
"
- Left click for full forecast.
- Middle click to update forecast.
: Chance of rain/snow
: Daily low
: Daily high" ;;
esac

if [ "$(stat -c %y "$HOME/.local/share/weatherreport" >/dev/null 2>&1 | awk '{print $1}')" != "$(date '+%Y-%m-%d')" ]
	then getforecast && showweather
	else showweather
fi

